services:
  - type: web
    name: car-price-prediction
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: ''
    startCommand: ''
    healthCheckPath: /health
